"""init 认知阶段的统一工具预算配置。"""

from __future__ import annotations

PCEIGNORE_STAGE_TOOL_BUDGET = 5
TOPOLOGY_NAVIGATION_STAGE_TOOL_BUDGET = 8
TOPOLOGY_REPAIR_STAGE_TOOL_BUDGET = 4
TOPOLOGY_INCREMENTAL_STAGE_TOOL_BUDGET = 8
TOPOLOGY_INCREMENTAL_REPAIR_STAGE_TOOL_BUDGET = 4
