"""init 认知阶段的统一预算与重试配置。"""

from __future__ import annotations

PCEIGNORE_STAGE_MAX_ATTEMPTS = 3
PCEIGNORE_STAGE_TOOL_BUDGET = 5
TOPOLOGY_STAGE_MAX_ATTEMPTS = 2
TOPOLOGY_NAVIGATION_STAGE_TOOL_BUDGET = 8
TOPOLOGY_REPAIR_STAGE_TOOL_BUDGET = 4
TOPOLOGY_AREA_STAGE_MAX_ATTEMPTS = 3
