from __future__ import annotations

import asyncio
import json
import tempfile
from datetime import UTC, datetime
from pathlib import Path
from types import SimpleNamespace

from pce.file_discovery import should_track_existing_file
from pce.memory import save_index
from pce.models import BuildStats, IndexSnapshot, ProjectMeta
from pce.server import PCEContext
from pce.staging import StagingArea


async def _write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, "utf-8")


async def _seed_existing_index(project_root: Path) -> None:
    now = datetime.now(UTC)
    snapshot = IndexSnapshot(
        project_meta=ProjectMeta(
            root_path=project_root,
            created_at=now,
            index_version="1",
            file_count=1,
            loc_total=1,
        ),
        entries=[],
        created_at=now,
        build_stats=BuildStats(
            total_files=0,
            total_symbols=0,
            total_edges=0,
            duration_ms=0,
            warnings=[],
        ),
    )
    await save_index(snapshot, root_path=project_root)


async def main() -> None:
    with tempfile.TemporaryDirectory(prefix="pceignore-refresh-dirty-") as tmp:
        project_root = Path(tmp)
        await _write_text(project_root / ".gitignore", "")
        await _write_text(project_root / "src" / "main.py", "print('hello')\n")
        await _seed_existing_index(project_root)

        noise_path = project_root / "vendor_cache" / "packages" / "react-18.0.0.js"
        await _write_text(noise_path, "console.log('fake package payload')\n")
        rel_noise = "vendor_cache/packages/react-18.0.0.js"

        staging = StagingArea(project_root)
        await staging.record_change(rel_noise)
        before_dirty = await staging.list_pending_reindex()
        assert rel_noise in before_dirty.changed
        assert should_track_existing_file(project_root, rel_noise) is True

        import pce.indexer as indexer_module

        original_refresh = indexer_module.run_pceignore_refresh_stage
        original_refresh_reason = indexer_module._annotation_refresh_reason

        async def _fake_refresh_stage(
            root_path: Path,
            _serena_client: object,
            *,
            changed_files: list[str],
            deleted_files: list[str] | None = None,
            model: str | None = None,
        ) -> str:
            del _serena_client, deleted_files, model
            assert rel_noise in changed_files
            current = root_path / ".pce" / "pceignore"
            existing = current.read_text("utf-8") if current.exists() else "# Auto-generated by test\n"
            if "vendor_cache/\n" not in existing and not existing.endswith("vendor_cache/"):
                existing = existing.rstrip() + "\nvendor_cache/\n"
            current.write_text(existing, "utf-8")
            return "updated"

        indexer_module.run_pceignore_refresh_stage = _fake_refresh_stage
        indexer_module._annotation_refresh_reason = lambda _root: None
        try:
            ctx = PCEContext()
            ctx._bound_path = project_root
            ctx._init_state = "initialized"
            ctx.staging = staging

            dirty = await ctx._run_index_refresh(SimpleNamespace())
            after_dirty = await staging.list_pending_reindex()

            assert rel_noise in dirty.changed
            assert after_dirty.empty
            assert should_track_existing_file(project_root, rel_noise) is False
            pceignore_text = (project_root / ".pce" / "pceignore").read_text("utf-8")
            assert "vendor_cache/" in pceignore_text
        finally:
            indexer_module.run_pceignore_refresh_stage = original_refresh
            indexer_module._annotation_refresh_reason = original_refresh_reason

    print(json.dumps({
        "ok": True,
        "tests": [
            "dirty 文件可先进入暂存区",
            "refresh 更新 ignore 后，同轮增量刷新会重新过滤该文件",
            "被新 ignore 的 dirty 条目会在本轮 refresh 后从 staging 清除",
            "refresh 产出的增量规则会立即影响 should_track_existing_file 判断",
        ],
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    asyncio.run(main())
